### PR TITLE
Bedrock block hitboxes

### LINKED ISSUE #918: Can't stand on chest on BDS server, weird visual bug (Bedrock).
### General Information

https://dump.viaversion.com/611317308ec2d1577453d3aacc46d809731aa0c2d315c697e196ced6c346588d

### Bug Description

After the latest commit [40a6ada3](https://github.com/ViaVersion/ViaFabricPlus/commit/40a6ada3d83c83dde76fcb2fda6cb159ce271eac) it's impossible to collide/stand on chest or ender chest, also weird visual bugs that allows you to see through walls. These two videos show the before and after.

https://github.com/user-attachments/assets/8a8860f8-2169-4da3-b98e-18c2092132ae
https://github.com/user-attachments/assets/fa80ea65-a927-44fb-b88f-6f83ec7eafbd

### Steps to Reproduce

1. Setup an BDS server, with `server-authoritative-movement-strict=true` and `player-position-acceptance-threshold` value anything between 0.025 to 1.0E-3 (ideally 1.0E-4)
2. Place any type of chest and walk on them.
3. Watch as the server repeatedly try to pull the player down, causing the player to fall down into the block and then being flagged up again.

### Expected Behavior

The player should be able to see the chest normally and also walk on the chest normally.

### PR DESCRIPTION
**Pull request by Exterminate5573**
Yes i tested them this time (sorry)

Fixes #918

### CODE REVIEW

File: src/main/java/com/viaversion/viafabricplus/injection/mixin/features/block/shape/MixinDoorBlock.java [hunk 1]
```diff
@@ -0,0 +1,77 @@
...
+    @Shadow
+    @Final
+    public static EnumProperty<DoorHinge> HINGE;
+
+    @Inject(method = "getOutlineShape", at = @At(value = "RETURN"), cancellable = true)
+    private void modifyCollisionShape(BlockState state, BlockView world, BlockPos pos, ShapeContext context, CallbackInfoReturnable<VoxelShape> cir) {
+        if (ProtocolTranslator.getTargetVersion().equals(BedrockProtocolVersion.bedrockLatest)) {
+            Direction direction = state.get(FACING);
+            Direction direction2 = (Boolean)state.get(OPEN) ? (state.get(HINGE) == DoorHinge.RIGHT ? direction.rotateYCounterclockwise() : direction.rotateYClockwise()) : direction;
+            cir.setReturnValue(viaFabricPlus$shape_bedrock.get(direction2));
```
Comment (FlorianMichael) [inline src/main/java/com/viaversion/viafabricplus/injection/mixin/features/block/shape/MixinDoorBlock.java]: Maybe Redirect on FIELD and just replace the shape if the Direction snippet is copied from the class

File: src/main/java/com/viaversion/viafabricplus/injection/mixin/features/block/shape/MixinTrapdoorBlock.java [hunk 2]
```diff
@@ -0,0 +1,79 @@
...
+    }
+
+    @Shadow
+    @Final
+    public static EnumProperty<BlockHalf> HALF;
+
+    @Inject(method = "getOutlineShape", at = @At(value = "RETURN"), cancellable = true)
+    private void modifyCollisionShape(BlockState state, BlockView world, BlockPos pos, ShapeContext context, CallbackInfoReturnable<VoxelShape> cir) {
+        if (ProtocolTranslator.getTargetVersion().equals(BedrockProtocolVersion.bedrockLatest)) {
+            cir.setReturnValue(viaFabricPlus$shape_bedrock.get(state.get(OPEN) ? state.get(FACING) : (state.get(HALF) == BlockHalf.TOP ? Direction.DOWN : Direction.UP)));
```
Comment (FlorianMichael) [inline src/main/java/com/viaversion/viafabricplus/injection/mixin/features/block/shape/MixinTrapdoorBlock.java]: same here, maybe just replace the map used using FIELD redirect

**Review by FlorianMichael — APPROVED** [review]
