### PR TITLE
Remove unused collision checks in versions <1.21.5

### LINKED ISSUE #873: [<= 1.21.4] Moving through cobwebs slows you down when it shouldn't
### General Information

ViaVersion dump url: https://dump.viaversion.com/d76b74b65e9a9d147c6d485d3c6307ed5be2ab928a7acfdf0b523f60640cecb1

### Bug Description

When moving through a cobweb, in 1.21.4 or earlier versions, if both positions before and after moving (1 game tick apart) are out of it, the player will get slowed down.

Fabric 1.21.8 with VFP, connected to a server in 1.21.4 (cobweb catches player even though it shouldn't):

https://github.com/user-attachments/assets/70526f55-da06-4ee3-aa2f-a1a172f5c37a

Diagram showing the bounding box of the player just before and right after jumping (arrows are collision order):
Diagram of the situation

### Steps to Reproduce

1. Join any server in a version prior to 1.21.5
2. Reproduce the shown setup
3. Sneak to the front of the block
4. Press W and Space simultaneously (closing the inventory with both keys held makes it consistent)
5. Observe that you get catched in the cobweb, whereas in any vanilla pre-1.21.5 version the game acts like nothing is blocking you

### Expected Behavior

In 1.21.4 and earlier versions, the game just wouldn't mind at all and would behave like no block was in the way.

Vanilla 1.21.4 in singleplayer (expected behavior):

https://github.com/user-attachments/assets/41738bf8-3fe5-4c0a-8ee9-e69662892e97

### PR DESCRIPTION
**Pull request by Exterminate5573**
Fixes #873

### CODE REVIEW

File: src/main/java/com/viaversion/viafabricplus/injection/mixin/features/movement/collision/MixinEntity.java [hunk 1]
```diff
@@ -163,4 +165,12 @@ private static boolean horizontalExactCollisionEqualness(double a, double b) {
         }
     }
 
+    @WrapMethod(method = "addQueuedCollisionChecks")
```
Comment (FlorianMichael) [inline src/main/java/com/viaversion/viafabricplus/injection/mixin/features/movement/collision/MixinEntity.java:168]: Should use WrapWithCondition, see other injectors for examples.

File: src/main/resources/viafabricplus.accesswidener [hunk 2]
```diff
@@ -1,5 +1,7 @@
 accessWidener v1 named
 
+accessible class net/minecraft/entity/Entity$QueuedCollisionCheck
```
Comment (FlorianMichael) [inline src/main/resources/viafabricplus.accesswidener:3]: Should be moved down to the last line where the other class accessor is.

**Review by FlorianMichael — CHANGES_REQUESTED** [review]

**Review by FlorianMichael — APPROVED** [review]
