### PR TITLE
Readd "air stepping" mechanic in <= 1.20.6

### LINKED ISSUE #454: Anticheats flagging because "air stepping" was removed in 1.21
### General Information

Minecraft 1.21 seems to have changed something that makes it so contraptions like these:
image
don't make the player step up the block anymore (sprint walk down from the red to the green)

### Bug Description

when using ViaFabricPlus to downgrade to an older protocol version, this doesn't get reverted.
anticheats that use movement prediction such as GrimAC will detect this deviation and flag.

### Steps to Reproduce

1. select any protocol version smaller than 1.21 (e.g. 1.20.6)
2. Build the setup shown earlier
3. stand on the red block and start sprinting forwards so that you are walking towards the green block.

### Expected Behavior

You step up the green block, and are now on it, this is how it works in older versions.

**Actual result:** You land on the blue block

P.S. this doesn't just happen with this specific setup, there are many scenarios where this same air stepping behavior might accidentally happen

### PR DESCRIPTION
**Pull request by RaphiMC**
Fixes #454

### CODE REVIEW

File: src/main/java/de/florianmichael/viafabricplus/injection/mixin/fixes/minecraft/entity/MixinEntity.java [hunk 1]
```diff
@@ -71,9 +74,48 @@ public abstract class MixinEntity implements IEntity {
...
+    public abstract boolean isOnGround();
+
+    @Shadow
+    public abstract float getStepHeight();
+
     @Unique
     private boolean viaFabricPlus$isInLoadedChunkAndShouldTick;
 
+    @Inject(method = "adjustMovementForCollisions(Lnet/minecraft/util/math/Vec3d;)Lnet/minecraft/util/math/Vec3d;", at = @At("HEAD"), cancellable = true)
+    private void use1_20_6StepCollisionCalculation(Vec3d movement, CallbackInfoReturnable<Vec3d> cir) {
```
Comment (FlorianMichael) [inline src/main/java/de/florianmichael/viafabricplus/injection/mixin/fixes/minecraft/entity/MixinEntity.java:90]:
```suggestion
    private void use1_20_5StepCollisionCalculation(Vec3d movement, CallbackInfoReturnable<Vec3d> cir) {
```

**Review by FlorianMichael — APPROVED** [review]
